export const questions = [
  {
    id: "dna-double-helix-year",
    category: "Science",
    prompt: "In what year did Watson and Crick determine the double-helix structure of DNA?",
    answer: 1953,
    unit: "year",
    displayAnswer: "1953",
    normalizer: 100,
    sourceName: "Nobel Prize",
    sourceUrl: "https://www.nobelprize.org/laureate/372"
  },
  {
    id: "speed-of-light",
    category: "Science",
    prompt: "What is the speed of light in vacuum, in metres per second?",
    answer: 299792458,
    unit: "m/s",
    displayAnswer: "299,792,458 m/s",
    normalizer: 299792458,
    sourceName: "NASA/JPL",
    sourceUrl: "https://ssd.jpl.nasa.gov/astro_par.html"
  },
  {
    id: "us-gdp-2023",
    category: "Economy",
    prompt: "What was nominal GDP of the United States in 2023, in current US dollars?",
    answer: 27720700000000,
    unit: "US dollars",
    displayAnswer: "$27.72 trillion",
    normalizer: 27720700000000,
    sourceName: "World Bank",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=US"
  },
  {
    id: "japan-gdp-2023",
    category: "Economy",
    prompt: "What was nominal GDP of Japan in 2023, in current US dollars?",
    answer: 4204490000000,
    unit: "US dollars",
    displayAnswer: "$4.20 trillion",
    normalizer: 4204490000000,
    sourceName: "World Bank / OICA referenced economic tables",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=JP"
  },
  {
    id: "australia-population-2023",
    category: "Population",
    prompt: "What was Australia's population in 2023?",
    answer: 26500000,
    unit: "people",
    displayAnswer: "about 26.5 million people",
    normalizer: 26500000,
    sourceName: "World Bank",
    sourceUrl: "https://data.worldbank.org/indicator/SP.POP.TOTL?locations=AU"
  },
  {
    id: "earth-sun-distance",
    category: "Astronomy",
    prompt: "What is the average Earth-Sun distance, in kilometres?",
    answer: 150000000,
    unit: "km",
    displayAnswer: "about 150 million km",
    normalizer: 150000000,
    sourceName: "NASA",
    sourceUrl: "https://science.nasa.gov/solar-system/cosmic-distances/"
  },
  {
    id: "eiffel-tower-height",
    category: "Landmark",
    prompt: "What is the current height of the Eiffel Tower including antenna, in metres?",
    answer: 330,
    unit: "metres",
    displayAnswer: "330 metres",
    normalizer: 330,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/topic/Eiffel-Tower-Paris-France"
  },
  {
    id: "mount-everest-height",
    category: "Geography",
    prompt: "What is the accepted height of Mount Everest, in metres?",
    answer: 8848.86,
    unit: "metres",
    displayAnswer: "8,848.86 metres",
    normalizer: 8848.86,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/place/Mount-Everest"
  },
  {
    id: "challenger-deep-depth",
    category: "Geography",
    prompt: "What is the approximate depth of Challenger Deep in the Mariana Trench, in metres?",
    answer: 10935,
    unit: "metres",
    displayAnswer: "about 10,935 metres",
    normalizer: 10935,
    sourceName: "NOAA Ocean Exploration",
    sourceUrl: "https://oceanexplorer.noaa.gov/dive-deeper/explainers-mapping/"
  },
  {
    id: "first-sunlike-exoplanet-year",
    category: "Astronomy",
    prompt: "In what year was 51 Pegasi b, the first exoplanet found orbiting a Sun-like star, discovered?",
    answer: 1995,
    unit: "year",
    displayAnswer: "1995",
    normalizer: 100,
    sourceName: "NASA",
    sourceUrl: "https://science.nasa.gov/universe/exoplanets/nobel-winners-changed-our-understanding-with-exoplanet-discovery/"
  },
  {
    id: "battle-of-hastings",
    category: "History",
    prompt: "In what year was the Battle of Hastings fought?",
    answer: 1066,
    unit: "year",
    displayAnswer: "1066",
    normalizer: 100,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/event/Battle-of-Hastings"
  },
  {
    id: "magna-carta",
    category: "History",
    prompt: "In what year was Magna Carta sealed at Runnymede?",
    answer: 1215,
    unit: "year",
    displayAnswer: "1215",
    normalizer: 100,
    sourceName: "US National Archives",
    sourceUrl: "https://www.archives.gov/exhibits/featured-documents/magna-carta"
  },
  {
    id: "fall-of-constantinople",
    category: "History",
    prompt: "In what year did Constantinople fall to the Ottoman Empire?",
    answer: 1453,
    unit: "year",
    displayAnswer: "1453",
    normalizer: 100,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/event/Fall-of-Constantinople-1453"
  },
  {
    id: "gutenberg-bible",
    category: "History",
    prompt: "Around what year was the Gutenberg Bible printed?",
    answer: 1455,
    unit: "year",
    displayAnswer: "about 1455",
    normalizer: 100,
    sourceName: "Library of Congress",
    sourceUrl: "https://guides.loc.gov/gutenberg"
  },
  {
    id: "columbus-americas",
    category: "History",
    prompt: "In what year did Columbus reach the Americas on his first voyage?",
    answer: 1492,
    unit: "year",
    displayAnswer: "1492",
    normalizer: 100,
    sourceName: "Library of Congress",
    sourceUrl: "https://www.loc.gov/exhibits/1492/"
  },
  {
    id: "storming-bastille",
    category: "History",
    prompt: "In what year was the Storming of the Bastille?",
    answer: 1789,
    unit: "year",
    displayAnswer: "1789",
    normalizer: 100,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/event/storming-of-the-Bastille"
  },
  {
    id: "wright-first-flight",
    category: "History",
    prompt: "In what year did the Wright brothers make the first powered, controlled airplane flight?",
    answer: 1903,
    unit: "year",
    displayAnswer: "1903",
    normalizer: 100,
    sourceName: "National Park Service",
    sourceUrl: "https://www.nps.gov/wrbr/learn/historyculture/thefirstflight.htm"
  },
  {
    id: "treaty-versailles",
    category: "History",
    prompt: "In what year was the Treaty of Versailles signed?",
    answer: 1919,
    unit: "year",
    displayAnswer: "1919",
    normalizer: 100,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/event/Treaty-of-Versailles-1919"
  },
  {
    id: "apollo-11-landing",
    category: "History",
    prompt: "In what year did Apollo 11 land humans on the Moon?",
    answer: 1969,
    unit: "year",
    displayAnswer: "1969",
    normalizer: 100,
    sourceName: "NASA",
    sourceUrl: "https://www.nasa.gov/mission/apollo-11/"
  },
  {
    id: "berlin-wall-fall",
    category: "History",
    prompt: "In what year did the Berlin Wall fall?",
    answer: 1989,
    unit: "year",
    displayAnswer: "1989",
    normalizer: 100,
    sourceName: "Britannica",
    sourceUrl: "https://www.britannica.com/question/When-did-the-Berlin-Wall-fall"
  },
  {
    id: "paris-berlin-distance",
    category: "Distance",
    prompt: "What is the straight-line distance from Paris to Berlin, in kilometres?",
    answer: 878,
    unit: "km",
    displayAnswer: "about 878 km",
    normalizer: 878,
    sourceName: "Distance Calculator",
    sourceUrl: "https://www.distancecalculator.net/from-paris-to-berlin"
  },
  {
    id: "london-edinburgh-distance",
    category: "Distance",
    prompt: "What is the straight-line distance from London to Edinburgh, in kilometres?",
    answer: 534,
    unit: "km",
    displayAnswer: "about 534 km",
    normalizer: 534,
    sourceName: "UK Distances",
    sourceUrl: "https://ukdistances.co.uk/en/england/london-gb/edinburgh-sct/"
  },
  {
    id: "madrid-barcelona-distance",
    category: "Distance",
    prompt: "What is the straight-line distance from Madrid to Barcelona, in kilometres?",
    answer: 505,
    unit: "km",
    displayAnswer: "about 505 km",
    normalizer: 505,
    sourceName: "Distance Calculator",
    sourceUrl: "https://www.distancecalculator.net/from-madrid-to-barcelona"
  },
  {
    id: "rome-milan-distance",
    category: "Distance",
    prompt: "What is the straight-line distance from Rome to Milan, in kilometres?",
    answer: 477,
    unit: "km",
    displayAnswer: "about 477 km",
    normalizer: 477,
    sourceName: "Distance Calculator",
    sourceUrl: "https://distancecalculator.io/Rome/Milan"
  },
  {
    id: "paris-london-distance",
    category: "Distance",
    prompt: "What is the straight-line distance from Paris to London, in kilometres?",
    answer: 344,
    unit: "km",
    displayAnswer: "about 344 km",
    normalizer: 344,
    sourceName: "Distance Calculator",
    sourceUrl: "https://www.distancecalculator.net/from-paris-to-london"
  },
  {
    id: "uk-population-2023",
    category: "Europe Population",
    prompt: "What was the UK population in mid-2023?",
    answer: 68300000,
    unit: "people",
    displayAnswer: "about 68.3 million people",
    normalizer: 68300000,
    sourceName: "Office for National Statistics",
    sourceUrl: "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/annualmidyearpopulationestimates/mid2023"
  },
  {
    id: "germany-population-2023",
    category: "Europe Population",
    prompt: "What was Germany's population at the end of 2023?",
    answer: 84700000,
    unit: "people",
    displayAnswer: "about 84.7 million people",
    normalizer: 84700000,
    sourceName: "Destatis",
    sourceUrl: "https://www.destatis.de/DE/Presse/Pressemitteilungen/2024/01/PD24_035_124.html"
  },
  {
    id: "france-population-2023",
    category: "Europe Population",
    prompt: "What was France's 2023 reference population?",
    answer: 68200000,
    unit: "people",
    displayAnswer: "about 68.2 million people",
    normalizer: 68200000,
    sourceName: "INSEE",
    sourceUrl: "https://www.insee.fr/fr/statistiques/8681011"
  },
  {
    id: "netherlands-population-2023",
    category: "Europe Population",
    prompt: "What was the Netherlands population in 2023?",
    answer: 17900000,
    unit: "people",
    displayAnswer: "about 17.9 million people",
    normalizer: 17900000,
    sourceName: "Statistics Netherlands",
    sourceUrl: "https://www.cbs.nl/en-gb/news/2024/01/population-growth-slower-in-2023"
  },
  {
    id: "spain-population-2023",
    category: "Europe Population",
    prompt: "What was Spain's population in 2023?",
    answer: 48600000,
    unit: "people",
    displayAnswer: "about 48.6 million people",
    normalizer: 48600000,
    sourceName: "INE Spain",
    sourceUrl: "https://www.ine.es/en/"
  },
  {
    id: "england-wales-live-births-2022",
    category: "Practical Data",
    prompt: "In England and Wales, how many live births were registered in 2022?",
    answer: 605479,
    unit: "births",
    displayAnswer: "605,479 live births",
    normalizer: 605479,
    sourceName: "Office for National Statistics",
    sourceUrl: "https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2022"
  },
  {
    id: "us-low-birthweight-2023",
    category: "Practical Data",
    prompt: "In the US in 2023, what percentage of babies were born low birthweight, under 2,500 grams?",
    answer: 8.58,
    unit: "percent",
    displayAnswer: "8.58%",
    normalizer: 100,
    sourceName: "CDC/NCHS",
    sourceUrl: "https://www.cdc.gov/nchs/fastats/birthweight.htm"
  },
  {
    id: "global-male-height-1996",
    category: "Practical Data",
    prompt: "What is the global average height of adult men born in 1996, in centimetres?",
    answer: 171,
    unit: "cm",
    displayAnswer: "about 171 cm",
    normalizer: 171,
    sourceName: "Our World in Data / NCD-RisC",
    sourceUrl: "https://ourworldindata.org/human-height"
  },
  {
    id: "global-female-height-1996",
    category: "Practical Data",
    prompt: "What is the global average height of adult women born in 1996, in centimetres?",
    answer: 159.5,
    unit: "cm",
    displayAnswer: "about 159.5 cm",
    normalizer: 159.5,
    sourceName: "Our World in Data / NCD-RisC",
    sourceUrl: "https://ourworldindata.org/human-height"
  },
  {
    id: "germany-car-registrations-2023",
    category: "Practical Data",
    prompt: "How many new passenger cars were registered in Germany in 2023?",
    answer: 2844609,
    unit: "cars",
    displayAnswer: "2,844,609 cars",
    normalizer: 2844609,
    sourceName: "KBA / OICA",
    sourceUrl: "https://www.oica.net/wp-content/uploads/pc_sales_2023.pdf"
  },
  {
    id: "oica-passenger-cars-2023",
    category: "Practical Data",
    prompt: "How many passenger cars were registered or sold by OICA members in 2023?",
    answer: 57013311,
    unit: "cars",
    displayAnswer: "about 57.0 million cars",
    normalizer: 57013311,
    sourceName: "OICA",
    sourceUrl: "https://www.oica.net/wp-content/uploads/pc_sales_2023.pdf"
  },
  {
    id: "nyc-yellow-taxis",
    category: "Practical Data",
    prompt: "How many yellow taxis are authorised by law in New York City?",
    answer: 13587,
    unit: "taxis",
    displayAnswer: "13,587 taxis",
    normalizer: 13587,
    sourceName: "NYC Taxi and Limousine Commission",
    sourceUrl: "https://www.nyc.gov/site/tlc/businesses/yellow-cab.page"
  },
  {
    id: "london-licensed-taxis-2023",
    category: "Practical Data",
    prompt: "How many licensed taxis were there in London in 2023?",
    answer: 15100,
    unit: "taxis",
    displayAnswer: "about 15,100 taxis",
    normalizer: 15100,
    sourceName: "UK Department for Transport",
    sourceUrl: "https://www.gov.uk/government/statistics/taxi-and-private-hire-vehicle-statistics-england-2023/taxi-and-private-hire-vehicle-statistics-england-2023"
  },
  {
    id: "tsa-passengers-2023",
    category: "Practical Data",
    prompt: "How many passengers did TSA screen at US airport checkpoints in 2023?",
    answer: 858000000,
    unit: "passengers",
    displayAnswer: "about 858 million passengers",
    normalizer: 858000000,
    sourceName: "TSA",
    sourceUrl: "https://www.tsa.gov/news/press/releases/2024/01/12/2023-year-review-tsa-highlights-year-innovation-and-improvements"
  },
  {
    id: "us-commute-time-2023",
    category: "Practical Data",
    prompt: "What was the average US one-way commute time in 2023, in minutes?",
    answer: 26.8,
    unit: "minutes",
    displayAnswer: "26.8 minutes",
    normalizer: 26.8,
    sourceName: "US Census Bureau",
    sourceUrl: "https://www.census.gov/topics/employment/commuting/guidance/acs-1yr.html"
  }
];
